# 스프링 부트가 외부 환경과 연결될 수 있도록 필요한 정보를 미리 알려주기 위해 설정을 추가
# 보통 어떤 db를 사용할지 정하고 연결할 때 작성, 환경이 바뀔 때나 어플리케이션 기능 확장 시 작성
# ------------------------------------
spring.application.name=spring_start
# 애플리케이션 이름을 정의
spring.datasource.url=jdbc:h2:tcp://localhost/~/test
# db가 어디에 있는지 알려주는 주소
spring.datasource.driver-class-name=org.h2.Driver
# db와 통신할 때 사용할 JDBC 드라이버 라이브러리를 지정
spring.datasource.username=sa
# db 접속을 위한 계정 이름
